<?php $helper = new Modules\Base\Model\Helper()?>

<!DOCTYPE html>
<html>
<head>
	<title>flex</title>
	<meta name="amount" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="public/css/main.css"/>
</head>


<body>
    <a href="<?=$helper->buildUrl()?>/logout"> Logout</a>
    <a href="<?=$helper->buildUrl()?>/changepin"> change pin</a>
    <a href="<?=$helper->buildUrl()?>/downloadrecept?name=statement">Download Statement</a>

    
    <h1 style='text-align:center'>Dashboard</h1>
    <h1><?php var_dump($_SESSION);?></h1>

    <form action="<?=$helper->buildUrl()?>/submit/dashboard" method="POST">
  <p>Please select the dinomination to withdraw:</p>
  <fieldset>

        <input type="radio" id="two-thousand" name="amount" value="2000">
        <label for="two-thousand">$2000</label><br>
        
        <input type="radio" id="one-thousand" name="amount" value="1000">
        <label for="one-thousand">$1000</label><br>
        
        <input type="radio" id="five-hundred" name="amount" value="500">
        <label for="five-hundred">$500</label><br>
        
        <input type="radio" id="two-hundred" name="amount" value="200">
        <label for="two-hundred">$200</label><br>
        
        <input type="radio" id="one-hundred" name="amount" value="100">
        <label for="one-hundred">$100</label><br>
        
        <input type="radio" id="fifty" name="amount" value="50">
        <label for="fifty">$50</label><br>
        
        <input type="radio" id="twenty" name="amount" value="20">
        <label for="twenty">$20</label><br>
        
        <input type="radio" id="ten" name="amount" value="10">
        <label for="ten">$10</label><br>
        
        <input type="radio" id="five" name="amount" value="5">
        <label for="five">$5</label><br>
        
        <input type="submit" value="Submit">
        </fieldset>



    </form>
</body>